### ISSUE TITLE
Method not aloowed when filtering related content

### ISSUE THREAD

**Issue by reithor** [netgen/TagsBundle#139]
_Tested on Ibexa Experience 3.3.6 (using netgen/tagsbundle 4.0.12):_

Error is thrown when filtering related content (use form on https://[host]/admin/tags/admin/tag/[tagid]/content):

```
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException:
No route found for "POST https://localhost:8000/admin/tags/admin/tag/1/content": Method Not Allowed (Allow: GET)

  at vendor/symfony/http-kernel/EventListener/RouterListener.php:140
  at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest()
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (vendor/symfony/http-kernel/HttpKernel.php:133)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:199)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:37)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:35)
  at require_once('/var/www/html/support/3.x/vendor/autoload_runtime.php')
     (public/index.php:5) 
```

Simple fix could be :

```
#bundle/Resources/config/routing/admin/tag.yaml
netgen_tags_admin_tag_related_content:
    path: /{tagId}/content
    controller: eztags.admin.controller.related_content:relatedContentAction
    methods: [GET, POST]
```
